import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import NavBar from '../componets/NavBar'
import MovieManager from '../componets/homecomps/MovieManager'
import PopularityManager from '../componets/homecomps/PopularityManager'

export default function Home() {
  return (
    <div>
      <Head>
        <title>INKT Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar></NavBar>
      <PopularityManager></PopularityManager>
      <MovieManager></MovieManager>
    </div>
  )
}
