import Container from "@mui/material/Container";
// import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link'
// import Header from '../components/Header'
import MovieManager from '../components/homecomps/MovieManager'
import PopularityManager from '../components/homecomps/PopularityManager'

const Homepage = () => {
  return (
    <Container maxWidth="sm">
      <div>
        {/* <Head>
          <title>INKT Movies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> */}
        {/* <Header></Header> */}
        <PopularityManager></PopularityManager>
        <MovieManager></MovieManager>
      </div>
    </Container>
  );
};

export default Homepage;
